"""
Fair-TSC global configuration.

ONE place to tune everything. All hyperparameters from the paper live here
with explicit references to the equation / section that motivates them.
"""

import os
import time

# ═══════════════════════════════════════════════════════════════════════
# Paths (auto-detected by platform: Windows local vs. Linux monaco)
# Override with env var FAIR_TSC_BASE_DIR if needed.
# ═══════════════════════════════════════════════════════════════════════
if os.environ.get("FAIR_TSC_BASE_DIR"):
    BASE_DIR = os.environ["FAIR_TSC_BASE_DIR"]
elif os.name == "nt":
    BASE_DIR = "C:/Users/ucemdc3/PycharmProjects/sumo-rl"
else:
    BASE_DIR = os.path.expanduser("~/sumo-rl")

# 4x4 grid: switch demand level by changing DEMAND_LEVEL.
# Files generated by generate_4x4_net.py and generate_routes_4x4.py.
DEMAND_LEVEL = "high"            # "low" / "medium" / "high"
NET_FILE     = os.path.join(BASE_DIR, "nets/4x4grid/4x4.net.xml")
ROUTE_FILE   = os.path.join(BASE_DIR, f"nets/4x4grid/4x4_{DEMAND_LEVEL}.rou.xml")

_TS = time.strftime("%Y%m%d_%H%M")
RUN_NAME   = f"fair_tsc_4x4_{DEMAND_LEVEL}_{_TS}"
OUTPUT_DIR = os.path.join(BASE_DIR, "outputs", RUN_NAME)
CKPT_DIR   = os.path.join(BASE_DIR, "checkpoints", RUN_NAME)

# ═══════════════════════════════════════════════════════════════════════
# SUMO simulation
# ═══════════════════════════════════════════════════════════════════════
NUM_SECONDS = 3600    # episode length (seconds of simulated time, T_ep)
DELTA_TIME  = 5       # seconds between agent decisions (Δt)
MIN_GREEN   = 5       # minimum green time before phase change allowed
USE_GUI     = False
LIBSUMO     = True    # set LIBSUMO_AS_TRACI=1 in env

STEPS_PER_EPISODE = NUM_SECONDS // DELTA_TIME  # = 720

# ═══════════════════════════════════════════════════════════════════════
# Reward — paper Eq. (15)
# R_i(t) = -Σ q^v_{i,k} - ω_p · Σ q^p_{i,c}
# ═══════════════════════════════════════════════════════════════════════
OMEGA_P = 1.0   # pedestrian queue weight — equal to vehicle queue weight (1:1)

# Reward scaling applied in sumo_env.step() — divides raw queue reward by
# this constant before returning to the training loop. Critic targets in 4x4
# high-demand are ~-3000 raw; scaling to ~-100 lets value_loss converge.
# Does not change the optimal policy (positive linear transform of reward).
REWARD_SCALE = 30.0

# ═══════════════════════════════════════════════════════════════════════
# Soft constraint budgets — paper Eq. (7), (11), (19)
# ═══════════════════════════════════════════════════════════════════════
D_P    = 0.05    # pedestrian non-compliance budget
D_S    = 0.05    # spillback budget — raised from 0.02 (4x4 high level produces
                 # non-zero C_s, tight budget would saturate λ^s)
T_MAX  = 0.02    # Theil budget (will lightly bind when IPPO baseline shows inter-
                 # intersection disparity from the arterial/local entry weighting)

# ═══════════════════════════════════════════════════════════════════════
# Training schedule — paper §III.D
# ═══════════════════════════════════════════════════════════════════════
T_WARM            = 7200      # Stage 1: UE warm-up — 10 episodes
                              # diag on 4x4 high w/ REWARD_SCALE=30 showed UE
                              # critic EV saturates at ep ~5-7 (0.94 -> 0.98);
                              # 10 ep leaves a 3-episode buffer past saturation
TOTAL_STEPS       = 300_000   # Stage 2: ~417 episodes — 4x4 + Lagrangian
                              # constraints needs more than 2x2's 100k
ROLLOUT_LENGTH    = 720       # one episode per rollout = 720 decision steps
PPO_EPOCHS        = 10
MINIBATCH_SIZE    = 512       # raised from 256 — buffer is 4x bigger now
BATCH_SIZE        = ROLLOUT_LENGTH * 16   # 16 agents × 720 steps = 11520

# ═══════════════════════════════════════════════════════════════════════
# Optimisation — paper §III.D ("two-timescale": η_λ, η_µ ≪ η_θ, η_φ)
# ═══════════════════════════════════════════════════════════════════════
ACTOR_LR    = 3e-4
CRITIC_LR   = 1e-3
ETA_LAMBDA  = 3e-3
ETA_MU      = 3e-2     # raised from 3e-4 (100x): prior 33h run on 4x4 high
                       # showed Theil saturating at 1.22 vs T_MAX=0.02, µ only
                       # reached 0.053 after 170 episodes -- way too slow.
                       # NOTE: this violates two-timescale (η_µ >> η_θ=3e-4);
                       # accepted because constraint must actually bind. Watch
                       # for µ oscillation in train_log; if it overshoots,
                       # back off to 1e-2.

GAMMA       = 0.99
GAE_LAMBDA  = 0.95
CLIP_EPS    = 0.2
ENTROPY_COEFF = 0.01
VF_COEFF      = 0.5
GRAD_CLIP     = 0.5
TAU_TGT       = 0.005   # Polyak target-network update (paper §III.D Eq. 33)

# ═══════════════════════════════════════════════════════════════════════
# Network architecture
# ═══════════════════════════════════════════════════════════════════════
ACTOR_HIDDEN  = [256, 256]   # actor takes local obs (D_l), 256 suffices
CRITIC_HIDDEN = [256, 256]   # critic takes global obs (D_g=16*D_l); if
                             # explained_var stays low, bump to [512, 512]
NUM_AGENTS    = 16           # 4x4 grid (re-checked at runtime)

# ═══════════════════════════════════════════════════════════════════════
# Theil index numerical safety — paper Eq. (18)
# ═══════════════════════════════════════════════════════════════════════
THEIL_EPS = 1e-6

# ═══════════════════════════════════════════════════════════════════════
# Logging
# ═══════════════════════════════════════════════════════════════════════
LOG_EVERY_N_EPISODES = 1
SAVE_CKPT_EVERY_N    = 50
SEED                 = 42
