"""
Generate three route files (low / medium / high demand) for the 4x4 grid net.

Style follows the original 2x2 generate_routes.py:
- 16 vehicle <flow>s (one per entry edge -> randomly chosen exit edge)
- 16 pedestrian <personFlow>s (one per entry edge -> randomly chosen exit edge)
- begin=0, end=3600 (1-hour horizon)
- Same OD pairs across the three levels (only base perHour scales)

Per-entry heterogeneity (NEW):
    Entries are split into two tiers and weighted to keep the network total
    identical to a uniform run, while creating intrinsic demand asymmetry
    across intersections. This gives the IPPO baseline a non-trivial Theil
    index even before MARL coordination kicks in, which is what the
    inter-intersection fairness motivation in the paper needs.

      Arterial (8 entries, weight 1.5):
          - East-West arterials through middle rows: -h21 -h31  h25 h35
          - North-South arterials through middle cols: -v21 -v31  v25 v35
      Local    (8 entries, weight 0.5):
          - All corner entries on the outer rows / cols:
            -h11 -h41  h15 h45  -v11 -v41  v15 v45

    Weighted sum = 8 * 1.5 + 8 * 0.5 = 16, so total network demand equals
    16 * base_perHour (same as the previous uniform version).

Base perHour per entry edge (BEFORE the tier weight is applied):
                low      medium     high
    vehicles    250      500        750    veh/h
    pedestrians 60       120        180    ped/h

Actual per-entry perHour = base * weight (1.5 arterial / 0.5 local).
At "high":  arterial = 750 * 1.5 = 1125 veh/h  (below ~1296 veh/h per-direction
            green-time capacity for a 2-lane edge with 37s green in ~104s cycle),
            local    = 750 * 0.5 = 375 veh/h.
Network total per level is unchanged from the uniform setting (16 * base).
"""

import argparse
import os
import random

GRID = 4
SIM_BEGIN = 0.0
SIM_END = 3600.0  # 1 hour

DEMAND = {
    "low":    {"veh": 250,  "ped": 60},
    "medium": {"veh": 500,  "ped": 120},
    "high":   {"veh": 750,  "ped": 180},
}

# ---------------------------------------------------------------------------
# Per-entry tier weights
# ---------------------------------------------------------------------------
ARTERIAL_WEIGHT = 1.5
LOCAL_WEIGHT    = 0.5

# Arterial entries: middle 2 rows (r=2,3) for E-W flow + middle 2 cols (c=2,3) for N-S flow
ARTERIAL_ENTRIES = set()
for r in (2, 3):
    ARTERIAL_ENTRIES.add(f"-h{r}1")  # West entry
    ARTERIAL_ENTRIES.add(f"h{r}5")   # East entry
for c in (2, 3):
    ARTERIAL_ENTRIES.add(f"-v{c}1")  # North entry
    ARTERIAL_ENTRIES.add(f"v{c}5")   # South entry


def entry_weight(entry_edge: str) -> float:
    return ARTERIAL_WEIGHT if entry_edge in ARTERIAL_ENTRIES else LOCAL_WEIGHT


# ---------------------------------------------------------------------------
# Entry / exit edges (must match the convention in generate_4x4_net.py)
# ---------------------------------------------------------------------------
def get_entries_exits():
    """Return (entries, exits) where each item is (side, edge_id)."""
    entries, exits = [], []
    for r in range(1, GRID + 1):
        entries.append(("W", f"-h{r}1"))
        exits.append(("W",   f"h{r}1"))
    for r in range(1, GRID + 1):
        entries.append(("E", f"h{r}5"))
        exits.append(("E",   f"-h{r}5"))
    for c in range(1, GRID + 1):
        entries.append(("N", f"-v{c}1"))
        exits.append(("N",   f"v{c}1"))
    for c in range(1, GRID + 1):
        entries.append(("S", f"v{c}5"))
        exits.append(("S",   f"-v{c}5"))
    return entries, exits


def reverse_edge(eid: str) -> str:
    """`-h11` <-> `h11`,  `v25` <-> `-v25`."""
    return eid[1:] if eid.startswith("-") else "-" + eid


def sample_od(entries, exits, rng):
    """For each entry, pick a random exit avoiding the self-reverse exit."""
    exit_edges = [e for _, e in exits]
    od = []
    for _, e_in in entries:
        cand = [e for e in exit_edges if e != reverse_edge(e_in)]
        e_out = rng.choice(cand)
        od.append((e_in, e_out))
    return od


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------
def write_rou(out_dir: str, level: str, veh_od, ped_od) -> str:
    base_v = DEMAND[level]["veh"]
    base_p = DEMAND[level]["ped"]
    total_v = sum(base_v * entry_weight(e_in) for e_in, _ in veh_od)
    total_p = sum(base_p * entry_weight(e_in) for e_in, _ in ped_od)

    path = os.path.join(out_dir, f"4x4_{level}.rou.xml")
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '',
        '<!-- generated by generate_routes_4x4.py -->',
        '<routes>',
        f'    <!-- demand={level}: arterial weight {ARTERIAL_WEIGHT}, '
        f'local weight {LOCAL_WEIGHT}, total {int(total_v)} veh/h + '
        f'{int(total_p)} ped/h -->',
    ]

    for e_in, e_out in veh_od:
        per_v = base_v * entry_weight(e_in)
        lines.append(
            f'    <flow id="f_{e_in}_to_{e_out}" '
            f'begin="{SIM_BEGIN:.2f}" end="{SIM_END:.2f}" '
            f'perHour="{per_v:.2f}" from="{e_in}" to="{e_out}" '
            f'departLane="best" departSpeed="max"/>'
        )

    for e_in, e_out in ped_od:
        per_p = base_p * entry_weight(e_in)
        lines.append(
            f'    <personFlow id="pf_{e_in}_to_{e_out}" '
            f'begin="{SIM_BEGIN:.2f}" end="{SIM_END:.2f}" '
            f'perHour="{per_p:.2f}">'
        )
        lines.append(f'        <personTrip from="{e_in}" to="{e_out}"/>')
        lines.append('    </personFlow>')

    lines.append('</routes>')

    with open(path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {path}  ({int(total_v)} veh/h + {int(total_p)} ped/h)")
    return path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main(out_dir: str = ".", seed: int = 42):
    os.makedirs(out_dir, exist_ok=True)
    entries, exits = get_entries_exits()
    rng = random.Random(seed)
    veh_od = sample_od(entries, exits, rng)
    ped_od = sample_od(entries, exits, rng)

    print(f"OD seed={seed}")
    print(f"Arterial entries (weight {ARTERIAL_WEIGHT}): "
          f"{sorted(ARTERIAL_ENTRIES)}")
    local_entries = [e for _, e in entries if e not in ARTERIAL_ENTRIES]
    print(f"Local    entries (weight {LOCAL_WEIGHT}): {sorted(local_entries)}")
    print()

    for level in ("low", "medium", "high"):
        write_rou(out_dir, level, veh_od, ped_od)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", default=".", help="Output directory")
    parser.add_argument("--seed", type=int, default=42, help="RNG seed")
    args = parser.parse_args()
    main(args.out_dir, args.seed)